web:
 image: tutum/apache-php
 ports:
   - "80:80"
 links:
   - db
 volumes:
   - $PWD:/app
 environment:
   ALLOW_OVERRIDE: "true"

db:
 image: mysql:5.6
 volumes:
       - db_data:/var/lib/mysql
 ports:
    - "1111:3306"
 restart: always
 environment:
   MYSQL_ROOT_PASSWORD: password
   MYSQL_DATABASE: lamp
   MYSQL_USER: root
   MYSQL_PASSWORD: password
